-- Tabela para armazenar as reuniões/aulas
CREATE TABLE public.meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    zoom_link TEXT NOT NULL,
    access_code TEXT NOT NULL UNIQUE,
    professor TEXT NOT NULL,
    theme TEXT NOT NULL,
    duration INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Tabela para armazenar os emails autorizados para cada reunião
CREATE TABLE public.authorized_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE(meeting_id, email)
);

-- Índices para melhorar a performance
CREATE INDEX meetings_access_code_idx ON public.meetings (access_code);
CREATE INDEX authorized_emails_meeting_id_idx ON public.authorized_emails (meeting_id);
CREATE INDEX authorized_emails_email_idx ON public.authorized_emails (email);

-- Políticas de segurança
-- Para produção, você deve configurar políticas de segurança apropriadas
-- Estas são apenas para demonstração

-- Permitir acesso anônimo para leitura de reuniões
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso anônimo para leitura de reuniões" 
ON public.meetings FOR SELECT USING (true);

-- Permitir acesso anônimo para inserção, atualização e exclusão de reuniões (em produção, isto seria restrito)
CREATE POLICY "Permitir acesso anônimo para inserção de reuniões" 
ON public.meetings FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir acesso anônimo para atualização de reuniões" 
ON public.meetings FOR UPDATE USING (true);

CREATE POLICY "Permitir acesso anônimo para exclusão de reuniões" 
ON public.meetings FOR DELETE USING (true);

-- Permitir acesso anônimo para leitura de emails autorizados
ALTER TABLE public.authorized_emails ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso anônimo para leitura de emails autorizados" 
ON public.authorized_emails FOR SELECT USING (true);

-- Permitir acesso anônimo para inserção, atualização e exclusão de emails autorizados (em produção, isto seria restrito)
CREATE POLICY "Permitir acesso anônimo para inserção de emails autorizados" 
ON public.authorized_emails FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir acesso anônimo para atualização de emails autorizados" 
ON public.authorized_emails FOR UPDATE USING (true);

CREATE POLICY "Permitir acesso anônimo para exclusão de emails autorizados" 
ON public.authorized_emails FOR DELETE USING (true); 